--CRUD FOR CATEGORY
ALTER PROC GenCrudCat
	@CHOICE VARCHAR(10),
	@CATID INT,
	@CATNAME VARCHAR(500) = null
AS
BEGIN
--INSERT
	IF @CHOICE = 'INSERT'
	BEGIN
		INSERT INTO gencategory VALUES (@CATID,@CATNAME)
	END
----UPDATE
	IF @CHOICE = 'UPDATE'
	BEGIN
		UPDATE gencategory SET CatName = @CATNAME WHERE Catid = @CATID  
	END
----DELETE
	IF @CHOICE = 'DELETE'
	BEGIN
		DELETE FROM gencategory WHERE Catid = @CATID
	END
END
GO

