--CRUD FOR CUSTOMER
ALTER PROC GenCrudOrders
	@CHOICE VARCHAR(10),
	@OID INT,
	@ORDERDATE DATE = null,
	@ORDERNUMBER VARCHAR(50)  = null,
	@CUSTOMERID INT = null,
	@CUSTOMERCATEGORYID INT =null
AS
BEGIN
--INSERT
	IF @CHOICE = 'INSERT'
	BEGIN TRY
		INSERT INTO genorders VALUES (@OID,@ORDERDATE,@ORDERNUMBER,@CUSTOMERID,@CUSTOMERCATEGORYID)
	END TRY
	BEGIN CATCH
	 PRINT Concat('Error_Message()=' , Error_Message());
	END CATCH
----UPDATE
	IF @CHOICE = 'UPDATE'
	BEGIN TRY
		UPDATE genorders SET OrderDate = @ORDERDATE, OrderNumber = @ORDERNUMBER, CusOrdid= @CUSTOMERID,CusCatOrdid = @CUSTOMERCATEGORYID WHERE Oid = @OID  
	END TRY
	BEGIN CATCH
	 PRINT Concat('Error_Message()=' , Error_Message());
	END CATCH
----DELETE
	IF @CHOICE = 'DELETE'
	BEGIN TRY
		DELETE FROM genorders WHERE Oid = @OID
	END TRY
	BEGIN CATCH
	 PRINT Concat('Error_Message()=' , Error_Message());
	END CATCH
END
GO

